#!/usr/bin/env node
/**
 * Reference implementation of the N-level Merkle branch verifier.
 * Mirrors verify_merkleN.rxd (as generated by gen_merkle.js).
 *
 * Branch format: Buffer of N × 33-byte entries.
 * Each entry: [direction byte][32-byte sibling hash].
 * direction 0x00 = sibling on right, else sibling on left.
 */

const crypto = require('crypto');

function hash256(buf) {
  return crypto.createHash('sha256').update(
    crypto.createHash('sha256').update(buf).digest()
  ).digest();
}

function verifyMerkle(leaf, branchBuf, expectedRoot) {
  if (branchBuf.length % 33 !== 0) throw new Error('branch length must be multiple of 33');
  const depth = branchBuf.length / 33;

  let current = Buffer.from(leaf);
  for (let i = 0; i < depth; i++) {
    const entry = branchBuf.slice(i * 33, (i + 1) * 33);
    const dir = entry[0];
    const sib = entry.slice(1, 33);

    if (dir === 0) {
      current = hash256(Buffer.concat([current, sib]));
    } else {
      current = hash256(Buffer.concat([sib, current]));
    }
  }

  return {
    computed: current,
    pass: current.equals(expectedRoot),
  };
}

// ===== Test: synthetic 4-leaf Merkle tree =====
//
//           root
//          /    \
//        AB      CD
//       /  \    /  \
//      A    B  C    D

const A = Buffer.from('aa'.repeat(80), 'hex');  // fake 80-byte tx for leaf A
const B = Buffer.from('bb'.repeat(80), 'hex');
const C = Buffer.from('cc'.repeat(80), 'hex');
const D = Buffer.from('dd'.repeat(80), 'hex');

const hA = hash256(A);
const hB = hash256(B);
const hC = hash256(C);
const hD = hash256(D);

const hAB = hash256(Buffer.concat([hA, hB]));
const hCD = hash256(Buffer.concat([hC, hD]));
const root = hash256(Buffer.concat([hAB, hCD]));

console.log('=== Synthetic 4-leaf Merkle tree ===');
console.log(`Leaf A:     ${hA.toString('hex')}`);
console.log(`Leaf B:     ${hB.toString('hex')}`);
console.log(`Node AB:    ${hAB.toString('hex')}`);
console.log(`Node CD:    ${hCD.toString('hex')}`);
console.log(`Root:       ${root.toString('hex')}`);
console.log('');

// Branch for tx A: [(dir=0, sib=hB), (dir=0, sib=hCD)]
// A's position: level 0, sibling B is on right (dir 0); level 1, sibling CD is on right (dir 0)
const branchA = Buffer.concat([
  Buffer.from([0x00]), hB,       // level 0
  Buffer.from([0x00]), hCD,      // level 1
]);
console.log('=== Test 1: tx A, valid branch ===');
let r = verifyMerkle(hA, branchA, root);
console.log(`  computed: ${r.computed.toString('hex')}`);
console.log(`  expected: ${root.toString('hex')}`);
console.log(`  Result:   ${r.pass ? 'PASS' : 'FAIL'}`);
if (!r.pass) { console.error('SANITY FAILURE'); process.exit(1); }

// Branch for tx B: [(dir=1, sib=hA), (dir=0, sib=hCD)]
const branchB = Buffer.concat([
  Buffer.from([0x01]), hA,       // B is right child at level 0, sibling A is on left
  Buffer.from([0x00]), hCD,      // AB is left child at level 1, sibling CD is on right
]);
console.log('=== Test 2: tx B, valid branch ===');
r = verifyMerkle(hB, branchB, root);
console.log(`  Result:   ${r.pass ? 'PASS' : 'FAIL'}`);
if (!r.pass) { console.error('SANITY FAILURE'); process.exit(1); }

// Branch for tx D: [(dir=1, sib=hC), (dir=1, sib=hAB)]
const branchD = Buffer.concat([
  Buffer.from([0x01]), hC,
  Buffer.from([0x01]), hAB,
]);
console.log('=== Test 3: tx D, valid branch ===');
r = verifyMerkle(hD, branchD, root);
console.log(`  Result:   ${r.pass ? 'PASS' : 'FAIL'}`);
if (!r.pass) { console.error('SANITY FAILURE'); process.exit(1); }

// --- Negative tests ---
console.log('=== Test 4: wrong leaf ===');
r = verifyMerkle(hC, branchA, root);  // using A's branch with C's hash
console.log(`  Result:   ${r.pass ? 'PASS (unexpected!)' : 'FAIL (as expected)'}`);
if (r.pass) { console.error('SANITY FAILURE'); process.exit(1); }

console.log('=== Test 5: flipped direction byte ===');
const branchAwrong = Buffer.from(branchA);
branchAwrong[0] = 0x01;  // flip first direction
r = verifyMerkle(hA, branchAwrong, root);
console.log(`  Result:   ${r.pass ? 'PASS (unexpected!)' : 'FAIL (as expected)'}`);
if (r.pass) { console.error('SANITY FAILURE'); process.exit(1); }

console.log('=== Test 6: tampered sibling ===');
const branchATampered = Buffer.from(branchA);
branchATampered[1] ^= 0xff;  // flip bits in first sibling hash
r = verifyMerkle(hA, branchATampered, root);
console.log(`  Result:   ${r.pass ? 'PASS (unexpected!)' : 'FAIL (as expected)'}`);
if (r.pass) { console.error('SANITY FAILURE'); process.exit(1); }

console.log('');
console.log('✓ Merkle branch verification correct for all positions (A, B, D).');
console.log('✓ Rejects wrong leaf.');
console.log('✓ Rejects wrong direction.');
console.log('✓ Rejects tampered sibling.');
