#!/usr/bin/env node
/**
 * Reference implementation of the Gravity N-header chain verifier.
 * Mirrors verify_chainN.rxd (as generated by gen_chain.js).
 *
 * For each header:
 *  1. Verify PoW (hash < target derived from nBits)
 *  2. Verify chain link: header[i].prevHash == hash256(header[i-1])
 *
 * Usage:
 *   node reference_chain.js
 */

const crypto = require('crypto');

function hash256(buf) {
  return crypto.createHash('sha256').update(
    crypto.createHash('sha256').update(buf).digest()
  ).digest();
}

function verifyPoW(header) {
  if (header.length !== 80) throw new Error(`expected 80-byte header, got ${header.length}`);
  const nBits = header.slice(72, 76);
  const mantissaLE = nBits.slice(0, 3);
  const exponent = nBits[3];

  const targetLE = Buffer.concat([
    Buffer.alloc(exponent - 3),
    mantissaLE,
    Buffer.alloc(32 - exponent),
  ]);

  const hashLE = hash256(header);
  const hBE = Buffer.from(hashLE).reverse();
  const tBE = Buffer.from(targetLE).reverse();

  for (let i = 0; i < 8; i++) {
    const h = hBE.readUInt32BE(i * 4);
    const t = tBE.readUInt32BE(i * 4);
    if (h < t) return { pass: true,  hashLE, hBE };
    if (h > t) return { pass: false, hashLE, hBE };
  }
  return { pass: false, hashLE, hBE };  // exactly equal
}

function verifyChain(headersHex) {
  const headers = headersHex.map(h => Buffer.from(h, 'hex'));
  const results = [];

  let prevHash = null;
  for (let i = 0; i < headers.length; i++) {
    const h = headers[i];

    // Chain link (for i > 0)
    let linkOk = true;
    if (i > 0) {
      const prevField = h.slice(4, 36);               // bytes [4..36] = prevHash field
      linkOk = prevField.equals(prevHash);
    }

    // PoW
    const pow = verifyPoW(h);

    results.push({
      index: i,
      hashLE: pow.hashLE.toString('hex'),
      hashBE: pow.hBE.toString('hex'),
      powOk: pow.pass,
      linkOk,
    });

    prevHash = pow.hashLE;
  }

  const allOk = results.every(r => r.powOk && r.linkOk);
  return { allOk, results };
}

// --- Real consecutive mainnet blocks 840000 + 840001 ---
const block840000 = '00e05f2aab948491071265ad552351d0ad625745668da54b0172010000000000000000004f89a5d73bd4d4887f25981fe81892ccafda10c27f52d6f3dd28183a7c411b03b7072366194203177d9863ea';
const block840001 = '04002020a583da1c3ff29b687248ff737822f8ce4827033a282003000000000000000000bcc07f8618b7b063f833100724e2b40d6ee9dfa78087bfbe5d3441058a63de380e082366194203176d9026cc';

console.log('=== Test 1: consecutive mainnet chain 840000 → 840001 ===');
const r = verifyChain([block840000, block840001]);
r.results.forEach(res => {
  console.log(`  [${res.index}] hashBE: ${res.hashBE}`);
  console.log(`       PoW: ${res.powOk ? 'PASS' : 'FAIL'}    Link: ${res.linkOk ? 'PASS' : 'FAIL'}`);
});
console.log(`  OVERALL: ${r.allOk ? 'PASS' : 'FAIL'}`);
if (!r.allOk) { console.error('SANITY FAILURE'); process.exit(1); }

console.log('');
console.log('=== Test 2: broken chain (swap order) ===');
const broken = verifyChain([block840001, block840000]);
broken.results.forEach(res => {
  console.log(`  [${res.index}] PoW: ${res.powOk ? 'PASS' : 'FAIL'}    Link: ${res.linkOk ? 'PASS' : 'FAIL'}`);
});
console.log(`  OVERALL: ${broken.allOk ? 'PASS (unexpected!)' : 'FAIL (as expected)'}`);
if (broken.allOk) { console.error('SANITY FAILURE'); process.exit(1); }

console.log('');
console.log('=== Test 3: tampered nonce on h2 ===');
const tamperedH2 = block840001.slice(0, -8) + '00000000';
const t = verifyChain([block840000, tamperedH2]);
t.results.forEach(res => {
  console.log(`  [${res.index}] PoW: ${res.powOk ? 'PASS' : 'FAIL'}    Link: ${res.linkOk ? 'PASS' : 'FAIL'}`);
});
console.log(`  OVERALL: ${t.allOk ? 'PASS (unexpected!)' : 'FAIL (as expected)'}`);
if (t.allOk) { console.error('SANITY FAILURE'); process.exit(1); }

console.log('');
console.log('✓ Chain verification logic correct against real mainnet consecutive blocks.');
console.log('✓ Broken chain correctly rejected.');
console.log('✓ Tampered successor header correctly rejected.');
