#!/usr/bin/env node
/**
 * Generator: emit a RadiantScript contract that verifies a depth-N
 * Bitcoin Merkle branch.
 *
 * Branch format: N × 33-byte chunks, each = [direction byte][32-byte sibling hash].
 * direction 0x00 = sibling on right, else sibling on left.
 *
 * Usage: node gen_merkle.js N > verify_merkleN.rxd
 */

const N = parseInt(process.argv[2] || '12', 10);
if (!(N >= 1 && N <= 32)) {
  console.error(`N must be 1..32, got ${process.argv[2]}`);
  process.exit(1);
}

function indent(lines, spaces = 12) {
  const pad = ' '.repeat(spaces);
  return lines.map(l => (l.length ? pad + l : l)).join('\n');
}

const lines = [];
lines.push(`pragma radiantscript ^0.1.0;`);
lines.push(``);
lines.push(`// Gravity prototype — depth-${N} Merkle branch verifier`);
lines.push(`// Auto-generated by gen_merkle.js. Do not edit by hand.`);
lines.push(`//`);
lines.push(`// Branch layout: ${N} × 33-byte entries =${' '}${N * 33} bytes total.`);
lines.push(`// Each entry: [direction (1B): 0x00=right sibling, else left] [sibling hash (32B)].`);
lines.push(``);
lines.push(`contract VerifyMerkle${N}() {`);
lines.push(`    return {`);
lines.push(`        check(bytes32 leaf, bytes branch, bytes32 expectedRoot) {`);
lines.push(`            bytes32 current = leaf;`);
lines.push(``);

for (let i = 0; i < N; i++) {
  // Offset-based extraction: fewer OP_DUPs than rolling-consumer pattern.
  const offsetExpr = i === 0 ? 'branch' : `branch.split(${i * 33})[1]`;
  lines.push(indent([
    `// --- Level ${i} ---`,
    `bytes lvl${i} = ${offsetExpr}.split(33)[0];`,
    `bytes dir${i} = lvl${i}.split(1)[0];`,
    `bytes sib${i} = lvl${i}.split(1)[1];`,
    `if (dir${i} == 0x00) {`,
    `    current = hash256(current + sib${i});`,
    `} else {`,
    `    current = hash256(sib${i} + current);`,
    `}`,
    ``,
  ]));
}

lines.push(`            require(current == expectedRoot);`);
lines.push(`        }`);
lines.push(`    };`);
lines.push(`}`);

console.log(lines.join('\n'));
