#!/usr/bin/env node
/**
 * Generator: emit a RadiantScript contract that verifies an N-header
 * Bitcoin chain (PoW on each header + prev_hash linking).
 *
 * Usage: node gen_chain.js N > verify_chainN.rxd
 */

const N = parseInt(process.argv[2] || '6', 10);
if (!(N >= 1 && N <= 144)) {
  console.error(`N must be 1..144, got ${process.argv[2]}`);
  process.exit(1);
}

function indent(lines, spaces = 12) {
  const pad = ' '.repeat(spaces);
  return lines.map(l => (l.length ? pad + l : l)).join('\n');
}

// PoW check for a single header slot `i` (1-indexed).
function powBlock(i) {
  const H = `h${i}`;
  return [
    `// --- PoW check: ${H} ---`,
    `bytes n${i} = ${H}.split(72)[1].split(4)[0];`,
    `bytes m${i} = n${i}.split(3)[0];`,
    `int e${i} = int(n${i}.split(3)[1]);`,
    `bytes t${i} = bytes(0, e${i} - 3) + m${i} + bytes(0, 32 - e${i});`,
    ``,
    `bytes32 hash${i} = hash256(${H});`,
    `bytes hBE${i} = hash${i}.reverse();`,
    `bytes tBE${i} = t${i}.reverse();`,
    ``,
    ...[0, 1, 2, 3, 4, 5, 6, 7].map(k => {
      const src = k === 0 ? `hBE${i}.split(4)[0]` :
                  k === 7 ? `hBE${i}.split(28)[1]` :
                            `hBE${i}.split(${k * 4})[1].split(4)[0]`;
      return `int h${i}c${k} = int(${src}.reverse());`;
    }),
    ...[0, 1, 2, 3, 4, 5, 6, 7].map(k => {
      const src = k === 0 ? `tBE${i}.split(4)[0]` :
                  k === 7 ? `tBE${i}.split(28)[1]` :
                            `tBE${i}.split(${k * 4})[1].split(4)[0]`;
      return `int t${i}c${k} = int(${src}.reverse());`;
    }),
    ``,
    `bool pow${i} =`,
    ...[0, 1, 2, 3, 4, 5, 6, 7].map((k, idx) => {
      const eqPart = [...Array(k).keys()].map(j => `(h${i}c${j} == t${i}c${j})`).join(' && ');
      const ltPart = `(h${i}c${k} < t${i}c${k})`;
      const expr = k === 0 ? ltPart : `(${eqPart} && ${ltPart})`;
      const sep = idx === 7 ? ';' : ' ||';
      return `    ${expr}${sep}`;
    }),
    `require(pow${i});`,
  ];
}

const lines = [];
lines.push(`pragma radiantscript ^0.1.0;`);
lines.push(``);
lines.push(`// Gravity prototype — ${N}-header chain verification`);
lines.push(`// Auto-generated by gen_chain.js. Do not edit by hand.`);
lines.push(``);
lines.push(`contract VerifyChain${N}() {`);
lines.push(`    return {`);

// Function signature: verify(bytes h1, bytes h2, ..., bytes hN)
const params = Array.from({ length: N }, (_, i) => `bytes h${i + 1}`).join(', ');
lines.push(`        verify(${params}) {`);

// Emit PoW for h1, chain-link+PoW for h2..hN
for (let i = 1; i <= N; i++) {
  if (i > 1) {
    // prev_hash check: h{i}.prevHash == hash256(h{i-1}) == hash{i-1}
    lines.push(indent([
      `// --- Chain link: h${i}.prevHash == hash${i - 1} ---`,
      `bytes prev${i} = h${i}.split(4)[1].split(32)[0];`,
      `require(prev${i} == hash${i - 1});`,
      ``,
    ]));
  }
  lines.push(indent(powBlock(i)));
  if (i < N) lines.push('');
}

lines.push(`        }`);
lines.push(`    };`);
lines.push(`}`);

console.log(lines.join('\n'));
